import mongoose from 'mongoose';

const timetableSlotSchema = new mongoose.Schema(
  {
    start: {
      type: Date,
      required: [true, 'Please provide a start time'],
    },
    end: {
      type: Date,
      required: [true, 'Please provide an end time'],
    },
    task: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Task',
      default: null,
    },
   status: {
  type: String,
  enum: ['free', 'scheduled', 'pending', 'done', 'skipped'],
  default: 'pending',
},

    autoGenerated: {
      type: Boolean,
      default: false,
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
  },
  {
    timestamps: true,
  }
  
);

export default mongoose.model('TimetableSlot', timetableSlotSchema);










